/**
 * generated by Xtext
 */
package dk.sdu.mmmi.sgl.validation;

import dk.sdu.mmmi.sgl.validation.AbstractSpreadsheetGrammarLanguageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SpreadsheetGrammarLanguageValidator extends AbstractSpreadsheetGrammarLanguageValidator {
}
