/*
 * generated by Xtext
 */
package dk.sdu.mmmi.sgl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.sdu.mmmi.sgl.ui.internal.SpreadsheetGrammarLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpreadsheetGrammarLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SpreadsheetGrammarLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SpreadsheetGrammarLanguageActivator.getInstance().getInjector(SpreadsheetGrammarLanguageActivator.DK_SDU_MMMI_SGL_SPREADSHEETGRAMMARLANGUAGE);
	}
	
}
