/*
 * generated by Xtext
 */
package dk.sdu.mmmi.sgl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpreadsheetGrammarLanguageRuntimeModule extends dk.sdu.mmmi.sgl.AbstractSpreadsheetGrammarLanguageRuntimeModule {

}
