/*
* generated by Xtext
*/
package dk.sdu.mmmi.sgl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SpreadsheetGrammarLanguageStandaloneSetup extends SpreadsheetGrammarLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new SpreadsheetGrammarLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

