/*
 * generated by Xtext
 */
package dk.sdu.mmmi.sgl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SpreadsheetGrammarLanguageUiModule extends dk.sdu.mmmi.sgl.ui.AbstractSpreadsheetGrammarLanguageUiModule {
	public SpreadsheetGrammarLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
