/*
* generated by Xtext
*/
package dk.sdu.mmmi.sgl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import dk.sdu.mmmi.sgl.services.SpreadsheetGrammarLanguageGrammarAccess;

public class SpreadsheetGrammarLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SpreadsheetGrammarLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected dk.sdu.mmmi.sgl.parser.antlr.internal.InternalSpreadsheetGrammarLanguageParser createParser(XtextTokenStream stream) {
		return new dk.sdu.mmmi.sgl.parser.antlr.internal.InternalSpreadsheetGrammarLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Grammar";
	}
	
	public SpreadsheetGrammarLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SpreadsheetGrammarLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
