/*
 * generated by Xtext
 */
package dk.sdu.mmmi.sgl.ui.contentassist

import dk.sdu.mmmi.sgl.ui.contentassist.AbstractSpreadsheetGrammarLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SpreadsheetGrammarLanguageProposalProvider extends AbstractSpreadsheetGrammarLanguageProposalProvider {
}
